import type { Metadata } from "next";
import {
  DotGothic16,
  Geist,
  Geist_Mono,
  Manrope,
  Montserrat,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Globals/Navbar";
import Footer from "@/components/Globals/footer";
import ContactIcon from "@/features/Contact/ContactIcon";
import LoaderOverlay from "@/features/LoaderOverlay";
import { ThemeProvider } from "@/Providers/ThemeProvider";
import AccentWrapper from "@/Wrapper/AccentWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const DotGothic = DotGothic16({
  variable: "--font-gothic",
  subsets: ["latin"],
  weight: "400",
});

const manRope = Manrope({
  variable: "--font-man-rope",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${DotGothic.variable} ${manRope.variable} ${montserrat.variable} antialiased md:w-[767px] mx-auto font-montserrat relative w-full`}
      >
        <ThemeProvider>
          <AccentWrapper>
            <Navbar />
            {children}
            <Footer />
            <ContactIcon />
            {/* <LoaderOverlay /> */}
          </AccentWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
